version: '3.8'

services:
  # Backend Django
  backend:
    build:
      context: .
      args:
        REQUIREMENTS_FILE: requirements-dev.txt
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: dev-secret-key
      DEBUG: 1
      ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
      DB_NAME: tickets_dev
      DB_USER: tickets
      DB_PASSWORD: tickets
      DB_HOST: db
      DB_PORT: 5432
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin123
      ADMIN_EMAIL: admin@example.com
    depends_on:
      - db
    networks:
      - tickets-network

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: tickets_dev
      POSTGRES_USER: tickets
      POSTGRES_PASSWORD: tickets
    ports:
      - "5433:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    networks:
      - tickets-network

  # Redis (para cache futuro)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tickets-network

volumes:
  postgres_dev_data:
  redis_data:


networks:
  tickets-network:
    driver: bridge
