# Generated by Django 5.1.2 on 2025-08-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
